package topics.git;
/*TODO:
*  THIS EXCERCISE HELP TO THE NEW DEVELOPERS TO UNDERSTAND GITS BASIC COMMANDS.
* 1. CREATE A NEW JAVA PROJECT
* 2. CREATE A GIT REPOSITORY WITH COMMAND: git init
* 3. CREATE A 3 NEW GIT BRANCHES DEV, QA, PROD.
* 4. UPDATE DEV BRANCH WHIT A NEW EXCERCISE.
* 5. CREATE GITHUB REPOSITORY AND PUSH THE CHANGES.
* */
public class GitConcepts {
}
